### ISSUE TITLE
Invalid write to stdout on Windows

### ISSUE THREAD

**Issue by jhermsmeier** [jhermsmeier/krautspace#3]
```
C:\Users\Jonas\Code>krautspace

[KRAUTSPACE] [OPEN] (a minute ago)
[STATUS] open for public
           events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at fprintf (C:\Users\Jonas\AppData\Roaming\npm\node_modules\krautspace\node_modules\tab\lib\tab.js:21:9)
    at Object.emit (C:\Users\Jonas\AppData\Roaming\npm\node_modules\krautspace\node_modules\tab\lib\tab.js:119:4)
    at C:\Users\Jonas\AppData\Roaming\npm\node_modules\krautspace\node_modules\tab\lib\tab.js:140:7
```

**Comment by jhermsmeier** [comment]
Fixed in 737c0ae by the `tab` update from 0.1.0 -> 1.0.0
